---
old_pkg:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine

pkgs:
  - docker-ce
  - containerd.io
  - docker-ce-cli  
