- name: Install repo packages
  yum:
   name: "{{ pkg_req }}"
   state: present
   update_cache: yes

- name: Import GPG key for Mysql
  rpm_key:
   state: present
   key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

- name: Enable Remi repo
  shell:
    cmd: yum-config-manager --enable remi-php73; yum-config-manager --disable remi-php54

- name: Install required packages
  yum:
   name: "{{ pkgs }}"
   state: present
   update_cache: yes
  notify: enable httpd  

- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Check if server needs restarting
  shell:
    cmd: needs-restarting -r
  register: reboot_code
  ignore_errors: yes

- name: Reboot server if needed
  reboot:
    reboot_timeout: 300
    test_command: uptime
  when: reboot_code.rc != 0

- name: Enable firewall port
  firewalld:
   immediate: yes
   state: enabled
   permanent: yes
   zone: public
   service: "{{ item }}"
  loop: "{{ firewall_rules }}"
