- name: SELinux Setup
  seboolean:
   name: httpd_can_connect_ldap
   persistent: yes
   state: yes

- name: Set file context
  sefcontext:
   setype: httpd_sys_rw_content_t
   target: "{{ syspass_directory }}/app/(config|backup|cache|temp)(/.*)?"
   state: present

- name: Restore context
  shell:
   cmd: restorecon -R -v "{{ syspass_directory }}"
