---
- name: enable apache2 
  systemd:
   name: "{{ item }}"
   state: restarted
   enabled: yes
  loop: "{{ httpd_svc }}"

- name: restart apache2
  systemd:
    name: apache2
    state: restarted
    enabled: yes
