---
pkg_req:
 - https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm 
 - http://rpms.remirepo.net/enterprise/remi-release-7.rpm


pkgs:
 - wget
 - httpd 
 - mysql-server 
 - git
 - epel-release
 - yum-utils
 - php
 - php-fpm
 - php-gd
 - php-intl
 - php-ldap
 - php-mbstring
 - php-mysqlnd
 - php-opcache
 - php-pdo
 - php-xml
 - php-zip
 - php-mcrypt
 - libsemanage-python
 - policycoreutils-python
 - php-di
 - phpunit
 - php-doctrine-common   

httpd_svc: 
 - httpd
 - mysqld

firewall_rules:
 - http
 - https

syspass_directory: /var/www/html/syspass
git_repo: https://github.com/nuxsmin/sysPass.git
syspass_conf_dirs:
 - "{{ syspass_directory }}/app/config"
 - "{{ syspass_directory }}/backup"
