- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: Add Docker Repo
  get_url:
    dest: /etc/yum.repos.d/docker.repo
    url: https://download.docker.com/linux/centos/docker-ce.repo
    mode: 0644
    owner: root
    group: root

- name: Install Docker Packages
  yum:
    name: "{{ pkgs }}"
    state: present
  notify: Start and enable docker
