- name: Create syspass web server directory
  file:
   state: directory
   path: "{{ syspass_directory }}"
   owner: www-data
   group: www-data
   recurse: yes

- name: Clone Syspass Git Project
  git:
   repo: "{{ git_repo }}"
   dest: "{{ syspass_directory }}"

- name: Check directory permissions
  file:
   state: directory
   path: "{{ syspass_directory }}"
   owner: www-data
   group: www-data
   mode: 0750
   recurse: yes


