- name: create script
  template:
    src: install_composer.sh.j2
    mode: 0755
    dest: /usr/local/bin/install_composer.sh

- name: Execute the script
  shell:
    cmd: cd "{{ syspass_directory }}"; /usr/local/bin/install_composer.sh

- name: Delete lock file
  file:
    state: absent
    path: "{{ syspass_directory}}/composer.lock"

- name: Install syspass dependencies
  shell:
    cmd: cd "{{ syspass_directory }}"; php composer.phar install --no-dev -n

- name: Copy syspass apache conf
  template:
    src: syspass.conf.j2
    dest: /etc/apache2/sites-enabled/syspass.conf
    mode: 0644
  notify: restart apache2
